baseURL = "https://github.com/Nezunoban/autonomusings"
languageCode = "en-us"
title = "Autonomusings"

theme = ["autono"]
relatedPosts = true
publishDir = "docs"
canonifyURLs = true

summaryLength = 20


## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

# summarylength = 30

#paginate = 5

## Site Settings
[params]
    author = "Autonomusings"
    # title = "Title"
    # description = "..."
    authorimage = "img/logo.png"
    authorimagesmall = "img/logosmall.svg"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "github"
    # please choose either GraphComment or Disqus
    #GraphCommentId = "..."
    
    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    github = "<username>"
    instagram = "<username>"
    xing = "<username>"
    linkedin = "<username>"
    twitter = "<username>"
    facebook = "<username>"
    stackoverflow = "<username>"
    telegram = "<username>"
    email = "your-email@example.com"

## Main Menu
[[menu.main]]
    name = "Musings"
    weight = 100
    identifier = "musings"
    url = "/musings/"
[[menu.main]]
    name = "Updates"
    identifier = "updates"
    weight = 200
    url = "/updates/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
