baseURL = "https://github.com/Nezunoban/autonomusings"
languageCode = "en-us"
title = "Autonomusings"

theme = ["autono"]
relatedPosts = true
## Test comment
publishDir = "docs"

authorimage = "/img/logo.png"